---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 31091
  selector:
    app: prometheus
